# Generated by Django 3.0.6 on 2021-09-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=110)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('date', models.DateField(default='04-09-2021')),
            ],
        ),
    ]
