# Generated by Django 3.0.6 on 2021-09-05 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0002_auto_20210905_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='userid',
        ),
        migrations.AddField(
            model_name='items',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
